//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@interface SSDRootListController : PSListController
{
}

- (void)DRMCheck:(_Bool)arg1;
- (id)doSha256:(id)arg1;
- (void)email;
- (void)getDataFrom:(id)arg1;
- (_Bool)hashCheck:(_Bool)arg1;
- (void)helpPage;
- (void)purchase;
- (id)readFromFile;
- (id)readPreferenceValue:(id)arg1;
- (void)resetDefaults;
- (void)respring;
- (void)restore;
- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
- (void)shutdownNow;
- (id)specifiers;
- (void)transfer;
- (void)twitter;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)website;
- (void)writeToStringFile:(id)arg1;

@end

